version: '3.8'

services:
  # 관문: API 게이트웨이
  ticket-gateway:
    image: sangwoooo/ticket-gateway:latest
    container_name: ticket-gateway
    ports:
      - "8080:8080" # 외부에서 오는 8080을 게이트웨이가 처리
    restart: always
    depends_on:
      - ticket-db
      - ticket-redis

  # 서비스: 주문 관리
  ticket-order-service:
    image: sangwoooo/ticket-order-service:latest
    container_name: ticket-order-service
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://ticket-db:3306/ticket_db
      - SPRING_DATA_REDIS_HOST=ticket-redis
    restart: always
    depends_on:
      - ticket-db
      - ticket-redis

  # 서비스: 회원 관리
  ticket-member-service:
    image: sangwoooo/ticket-member-service:latest
    container_name: ticket-member-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ticket-db:3306/ticket_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul

      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    restart: always
    depends_on:
      - ticket-db

  # 인프라: MySQL
  ticket-db:
    image: mysql:8.0
    container_name: ticket-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 800M
    restart: always

  # 인프라: Redis
  ticket-redis:
    image: redis:7.2-alpine
    container_name: ticket-redis
    ports:
      - "6379:6379"
    restart: always

  ticket-ai-service:
    image: sangwoooo/ticket-ai-service:latest
    container_name: ticket-ai-service
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://ticket-db:3306/ticket_db
      - SPRING_DATA_REDIS_HOST=ticket-redis
      - SPRING_AI_VECTORSTORE_QDRANT_HOST=192.168.25.35
      - SPRING_AI_VECTORSTORE_QDRANT_PORT=6334

      - SPRING_AI_GOOGLE_GENAI_API_KEY=${GEMINI_API_KEY}
      - SPRING_AI_GOOGLE_GENAI_EMBEDDING_API_KEY=${GEMINI_API_KEY}
    restart: always
    depends_on:
      - ticket-db
      - ticket-redis

  # vector DB
#  qdrant:
#    image: qdrant/qdrant:latest
#    container_name: qdrant-ai-db
#    profiles:
#      - local
#    ports:
#      - "6333:6333"
#    volumes:
#      - ./qdrant_data:/qdrant.storage
