spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: memer-service-public
              uri: http://localhost:8081
              predicates:
                - Path=/api/member/login, /api/member/join

            - id: member-service-private
              uri: http://localhost:8081
              predicates:
                - Path=/api/member/**
              filters:
                - JwtAuthenticationFilter


jwt:
  secret: cr7siuucr7siuucr7siuucr7siuucr7siuucr7siuucr7siuucr7siuu
  access-expiration: 3600000 # 1시간
  refresh-expiration: 1209600000 # 14일