

spring:
  application:
    name: ticket-ai-service

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
        embedding:
          text:
            options:
              model: text-embedding-004
          api-key: ${GEMINI_API_KEY}




    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: ticket-performances
server:
  port: 8083