spring:
  application:
    name: ticket-ai-service

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
        embedding:
          text:
            options:
              model: gemini-embedding-001
              # Qdrant 벡터 DB와의 호환성을 위해 768차원으로 출력하라고 구글에 지시
              dimensions: 768
          api-key: ${GEMINI_API_KEY}




    vectorstore:
      qdrant:
        host: qdrant-ai-db
        port: 6334
        collection-name: ticket-performances
server:
  port: 8083