spring:
  r2dbc:
    url: r2dbc:pool:mysql://3.39.123.195:3306/ticket_db
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8082
jwt:
  secret: cr7siuucr7siuucr7siuucr7siuucr7siuucr7siuucr7siuucr7siuu
  access-expiration: 3600000 # 1시간
  refresh-expiration: 1209600000 # 14일

reservation-expire-minute: 5


#logging:
#  level:
#    org.springframework.r2dbc: DEBUG    # R2DBC 트랜잭션 흐름 확인
#    org.springframework.transaction: DEBUG # 트랜잭션 시작/종료 확인