spring:
  r2dbc:
    url: r2dbc:mysql://3.39.123.195:3306/ticket_db
    username: root
    password: root
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: pkc-gq2xn.asia-northeast3.gcp.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all # 리더, 팔로워 브로커 모두 메시지 잘 받았는지 확인(데이터 유실 방지)
    security:
      protocol: SASL_SSL
    properties:
      delivery.timeout.ms: 120000
      sasl.mechanism: PLAIN
      sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="STPOK3ZQPT3IUBKW" password="cflt8GGp4tclzIjSBS0F56g4nSqZeiHJPMQiU8vMTHaMIt9wCSIiRDzsXIJECViA";'


    consumer:
      max-poll-records: 100
      properties:
        # 메시지가 적을 때 최대 1초까지만 기다렸다가 배치를 실행
        fetch.max.wait.ms: 1000
        # 메시지가 1MB 쌓이면 시간 안 돼도 바로 실행
        fetch.min.bytes: 1048576

    listener:
      type: batch
server:
  port: 8082
jwt:
  secret: cr7siuucr7siuucr7siuucr7siuucr7siuucr7siuucr7siuucr7siuu
  access-expiration: 3600000 # 1시간
  refresh-expiration: 1209600000 # 14일

reservation-expire-minute: 3

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}



#logging:
#  level:
#    org.springframework.r2dbc: DEBUG    # R2DBC 트랜잭션 흐름 확인
#    org.springframework.transaction: DEBUG # 트랜잭션 시작/종료 확인