name: MSA CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # 상우님 브랜치명이 main인지 확인!

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 1. 게이트웨이 빌드 및 푸시
      - name: Build and push Gateway
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: MODULE_NAME=ticket-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ticket-gateway:latest

      # 2. 주문 서비스 빌드 및 푸시
      - name: Build and push Order Service
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: MODULE_NAME=ticket-order-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ticket-order-service:latest

      # 3. 회원 서비스 빌드 및 푸시
      - name: Build and push Member Service
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: MODULE_NAME=ticket-member-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ticket-member-service:latest

      # 3. AWS EC2 배포 명령
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/ticket-fast
            sudo docker compose pull
            sudo docker compose up -d
            sudo docker image prune -f